[package]
name = "matrix-print-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
chrono = "0.4"
clap = { version = "4.5.4", features = ["derive"] }

[[bin]]
name = "mpg"
path = "src/main.rs"
